### ISSUE TITLE
Bug: When it is nuxt3 added as a plug-in, an error occurs and it cannot be used

### ISSUE THREAD

**Issue by KahrLu** [gtm-support/vue-gtm#178] opened 2022-04-14 10:30 UTC
Hi,
   when I add vue-gtm as a plugins into nuxt3, there display errors in browser and $gtm doesn't work.
   Could you help me if this caused by the problem of writing, or is it incompatible with nuxt3 at present?
![image](https://user-images.githubusercontent.com/76502123/163367366-b3d71b92-6ed0-42c5-b47c-c36746c6907f.png)
![image](https://user-images.githubusercontent.com/76502123/163367800-bebc1750-6593-4f2f-ad89-b7a2df188688.png)
![image](https://user-images.githubusercontent.com/76502123/163369509-b707a6e5-7e46-44d5-a933-3e7472adfcd0.png)

**Comment by Shinigami92** [comment] 2022-04-14 10:38
I don't know how Nuxt3 works 🤷 
You could provide a minimal reproduction or post an answer when you found out how it correctly works

**Comment by Shinigami92** [comment] 2022-05-23 15:47
I'm not sure what this issue could be. Did you use the correct version of the plugin?
There are two different, one for vue 2 and one for vue 3
Beside that, reading the errors it looks like you use a minifier so the errors are not well readable.

Closing it for now, you are free to reopen and provide additional info

**Closed by Shinigami92** 2022-05-23 15:47 UTC
